[build]
  publish = "."
  command = ""

[[redirects]]
  from = "https://appwhatweather.netlify.app/*"
  to = "https://whatweather.xyz/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/about"
  to = "/about/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
